// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzxvjrecoinunnqkgzrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6eHZqcmVjb2ludW5ucWtnenJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5ODQ2MTIsImV4cCI6MjA3NDU2MDYxMn0.VvYot4JH7i82qvyoEHNg5Z0YjwTAYmMV-lfNqETFdZQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});